name: end-to-end

on:
  pull_request:
  push:

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
      - uses: browser-actions/setup-firefox@v1

      - run: npm install
      - run: npm run test:e2e
